apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-svc
  namespace: todo-app-v4
spec:
  type: NodePort
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
