apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secret
  namespace: todo-app-v4
type: Opaque
stringData:
  # Backend secrets
  APP_NAME: "Todo App - Phase II"
  DEBUG: "true"
  DATABASE_URL: "postgresql://neondb_owner:npg_xTGORHo47KsW@ep-hidden-night-ah5dqnpc.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require"

  JWT_EXPIRATION_HOURS: "1"
  CORS_ORIGINS: '["http://localhost:3000","http://localhost:3001","http://localhost:3002"]'
  GEMINI_API_KEY: "AIzaSyAJhyVk7rS_xD6zgu_ti-789IFesZeT0O0"

  # Frontend secrets
  NEXT_PUBLIC_API_URL: "http://todo-backend:8000"
  BETTER_AUTH_URL: "http://localhost:3000"
  DATABASE_URL: "postgresql://neondb_owner:npg_xTGORHo47KsW@ep-hidden-night-ah5dqnpc.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require"
